### ISSUE TITLE
Subscriptions Data Table

### ISSUE THREAD

**Issue by ziggysauce** [jduong09/water-your-subs#23]
This will be a work in progress for now, but here are some of my initial thoughts:

[UPDATED PER CONVERSATION BELOW]
```sql
id::SERIAL -- sequential primary key
name::TEXT -- name of subscription
nickname::TEXT -- user-defined nickname for subscription
created::TIMESTAMP WITH TIME ZONE -- timestamp of creation
removed::TIMESTAMP WITH TIME ZONE -- timestamp of deletion
due_date::TIMESTAMP WITH TIME ZONE -- indicates when the payment is due
reminder_days::INTEGER -- indicates how many days prior to the `due_date` the user wants to be reminded of the subscription
amount::INTEGER -- stored as cents, this is the amount due for the subscription
user_id::BIGINT -- the user_id that references the `users` table
PRIMARY KEY( id )
```

Some notes/considerations:
- Right now this schema will only apply to monthly-recurring subscriptions. For things that are weekly or on a different cadence, we'll want to devise a different strategy for `due_date`. One option would be to make it a date and have it just update to the next date after it's passed.... I'm thinking this may be better but I'll wait to see what you have to say.

**Comment by jduong09** [comment]
The table looks good. Making the due date a date and then adding calculating the next date sounds good to me, I think that will be best. Want me to add the table to the database or do you want to do it?

**Comment by ziggysauce** [comment]
Yeah I'm kinda leaning towards that too. Glad we agree.

And let's hold off for right now. We'll want to either (1) write in a system that allows us to update our database with "migrations" so that the upstream service can be updated in sync with our code or (2) just handle it all manually and ensure that we have a way to do a database pull in order to sync up our data.

Another thought I had is that we'll actually want to deploy this app fairly early on and then implement continuous integration. This way we can test/troubleshoot all the deployment issues early on and then build onto it with each new promotion. I'm learning the hard way that doing an entire project in dev to then only deploy at the very end has some issues hahaha
